# Prometheus configuration for Agent Skeptic Bench monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: 'agent-skeptic-bench'
    environment: 'production'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics
  - job_name: 'agent-skeptic-bench'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics via Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Python application metrics
  - job_name: 'python-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    honor_labels: true

  # Database metrics (if applicable)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if applicable)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

# Remote write configuration for long-term storage
remote_write:
  - url: "https://your-remote-prometheus.com/api/v1/write"
    headers:
      X-Project: "agent-skeptic-bench"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop